baseurl = "/"
canonifyurls = true
disqusShortname = "spf13"
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
theme = "hugo-theme-casper"
title = "Hugo Blog"
[params]
RSSLink = "http://feeds.feedburner.com/..."
author = "Product Manager"
authorlocation = "USA"
authorwebsite = "http://www.google.com"
bio = "my bio"
cover = "images/cover.jpg"
description = "SD this is my description"
githubName = "vjeantet"
googleAnalyticsUserID = "UA-79101-12"
hideHUGOSupport = false
logo = "images/logo.png"
twitterName = "vjeantet"
[params.social]
twitter = "your_twitter"
