baseurl = "/"
canonifyurls = true
disqusShortname = "spf13"
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
theme = "hugo-theme-casper"
title = "Casper Theme"
[params]
RSSLink = "http://feeds.feedburner.com/..."
author = "Valère JEANTET"
authorlocation = "Paris, France"
authorwebsite = "http://vjeantet.fr"
bio = "my bio"
cover = "images/cover.jpg"
description = "this is my description"
githubName = "vjeantet"
googleAnalyticsUserID = "UA-79101-12"
hideHUGOSupport = false
logo = "images/logo.png"
twitterName = "vjeantet"
[params.social]
twitter = "your_twitter"
